In [2]:
import torch.nn as nn

class Encoder(nn.Module):
    def __init__(self, color_dim, hidden_dim):
        """
        Simple Encoder model based on a GRU cell.

        Parameters
        ----------
        color_dim : int

        hidden_dim : int

        """
        super().__init__()
        self.color_dim = color_dim
        self.hidden_dim = hidden_dim
        self.rnn = nn.GRU(
            input_size=self.color_dim,
            hidden_size=self.hidden_dim,
            batch_first=True)

In [13]:
def listener_predictions(self, color_seqs, word_seqs, device=None):
    gold = []
    predicted = []
    correct = 0
    for color_seq, word_seq in zip(color_seqs, word_seqs):
        target_index = len(color_seq) - 1
        min_perp, pred, pred_index = self.listener_predict_one(
            color_seq, word_seq, device=device)
        gold.append(target_index)
        predicted.append(pred_index)
    return gold, predicted

In [26]:
list(zip(seqs, ans))

[([array([0.50044321, 0.53957182]),
   array([0.88611464, 0.98794238]),
   array([0.10714762, 0.05733771])],
  ['<s>', 'A', 'B', '</s>']),
 ([array([0.50487708, 0.44819377]),
   array([0.92395617, 0.85048364]),
   array([0.03585337, 0.18360977])],
  ['<s>', 'A', '</s>']),
 ([array([0.41580385, 0.59185956]),
   array([0.89179955, 0.84864158]),
   array([0.07088822, 0.15898727])],
  ['<s>', 'A', 'B', '</s>']),
 ([array([0.56561242, 0.41612338]),
   array([0.99833494, 0.92997889]),
   array([0.13944726, 0.05999493])],
  ['<s>', 'A', '</s>']),
 ([array([0.47543391, 0.49520102]),
   array([0.92734962, 0.94056903]),
   array([0.0063369 , 0.08105566])],
  ['<s>', 'A', 'B', '</s>'])]

In [16]:
seqs = [[array([0.50044321, 0.53957182]),
  array([0.88611464, 0.98794238]),
  array([0.10714762, 0.05733771])],
 [array([0.50487708, 0.44819377]),
  array([0.92395617, 0.85048364]),
  array([0.03585337, 0.18360977])],
 [array([0.41580385, 0.59185956]),
  array([0.89179955, 0.84864158]),
  array([0.07088822, 0.15898727])],
 [array([0.56561242, 0.41612338]),
  array([0.99833494, 0.92997889]),
  array([0.13944726, 0.05999493])],
 [array([0.47543391, 0.49520102]),
  array([0.92734962, 0.94056903]),
  array([0.0063369 , 0.08105566])]]

In [18]:
ans = [['<s>', 'A', 'B', '</s>'],
 ['<s>', 'A', '</s>'],
 ['<s>', 'A', 'B', '</s>'],
 ['<s>', 'A', '</s>'],
 ['<s>', 'A', 'B', '</s>']]

In [19]:
ans

[['<s>', 'A', 'B', '</s>'],
 ['<s>', 'A', '</s>'],
 ['<s>', 'A', 'B', '</s>'],
 ['<s>', 'A', '</s>'],
 ['<s>', 'A', 'B', '</s>']]

In [24]:
for i, seq in enumerate(seqs):
    print(seq[2], ans[i])

[0.10714762 0.05733771] ['<s>', 'A', 'B', '</s>']
[0.03585337 0.18360977] ['<s>', 'A', '</s>']
[0.07088822 0.15898727] ['<s>', 'A', 'B', '</s>']
[0.13944726 0.05999493] ['<s>', 'A', '</s>']
[0.0063369  0.08105566] ['<s>', 'A', 'B', '</s>']
